# ========== General ========== #
theme = 'catppuccin-mocha'
editor = "vscodium"
dir_editor = "superfile"

auto_check_update = false

cd_on_quit = true
shell_close_on_success = true

default_open_file_preview = true
show_image_preview = false
show_panel_footer_info = true
file_size_use_si = false

default_directory = "."

default_sort_type = 0
sort_order_reversed = false
case_sensitive_sort = false

debug = false

# ========== Style ========== #
code_previewer = 'bat'
nerdfont = true
transparent_background = true

show_image_preview = true
file_preview_width = 0
sidebar_width = 20

border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'

# ========== Plugins ========== #
metadata = false # needs exiftool
enable_md5_checksum = false

enable_content_search = true
content_searcher = "rg"
content_search_flags = ["--line-number", "--color", "never"]